services:
  app:
    image: serversideup/php:8.4-fpm-nginx
    container_name: laravel-inertia-app
    ports:
      - "8088:8080"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - SSL_MODE=off
      - AUTORUN_ENABLED=true
      - AUTORUN_LARAVEL_STORAGE_LINK=true
      - AUTORUN_LARAVEL_MIGRATION=true
      - PHP_OPCACHE_ENABLE=0 # Disable OPcache for development
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel-network

  queue:
    image: serversideup/php:8.4-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "php", "artisan", "horizon" ]
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel-network
    restart: unless-stopped

  scheduler:
    image: serversideup/php:8.4-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    stop_signal: SIGTERM
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck-schedule" ]
      start_period: 10s

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - laravel-network

  node:
    build:
      context: .
      dockerfile: Dockerfile.node-php
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
